-- Create Celcius table
create table celcius (
  id bigint generated by default as identity primary key,
  degrees integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Humidity table
create table humidity (
  id bigint generated by default as identity primary key,
  percent integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Relay table
create type relay_status as enum ('ON', 'OFF');
create type relay_mode as enum ('AUTO', 'MANUAL');

create table relay (
  id bigint generated by default as identity primary key,
  reported_status relay_status not null,
  mode relay_mode not null,
  manual_since timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
